image: jmciver/gcc-boost-cmake:latest
pipelines:
  default:
    - step:
        script:
          - mkdir -p build/debug
          - cd build/debug
          - cmake -DCMAKE_BUILD_TYPE=Debug -DTESTING=ON ../../src
          - make
          - ctest
